#ifndef CODE_PROJECT_VERSION_H
#define CODE_PROJECT_VERSION_H

#define CODE_PROJECT_VERSION_MAJOR 1
#define CODE_PROJECT_VERSION_MINOR 0
#define CODE_PROJECT_VERSION_PATCH 0
#define CODE_PROJECT_VERSION_STRING "1.0.0"

#endif  // CODE_PROJECT_VERSION_H
