// Auto-generated. Do not edit!

// (in-package maita_can_comm.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CANCommGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.can_id = null;
      this.data = null;
      this.dlc = null;
      this.extended = null;
      this.channel = null;
    }
    else {
      if (initObj.hasOwnProperty('can_id')) {
        this.can_id = initObj.can_id
      }
      else {
        this.can_id = 0;
      }
      if (initObj.hasOwnProperty('data')) {
        this.data = initObj.data
      }
      else {
        this.data = [];
      }
      if (initObj.hasOwnProperty('dlc')) {
        this.dlc = initObj.dlc
      }
      else {
        this.dlc = 0;
      }
      if (initObj.hasOwnProperty('extended')) {
        this.extended = initObj.extended
      }
      else {
        this.extended = false;
      }
      if (initObj.hasOwnProperty('channel')) {
        this.channel = initObj.channel
      }
      else {
        this.channel = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CANCommGoal
    // Serialize message field [can_id]
    bufferOffset = _serializer.uint32(obj.can_id, buffer, bufferOffset);
    // Serialize message field [data]
    bufferOffset = _arraySerializer.uint8(obj.data, buffer, bufferOffset, null);
    // Serialize message field [dlc]
    bufferOffset = _serializer.uint8(obj.dlc, buffer, bufferOffset);
    // Serialize message field [extended]
    bufferOffset = _serializer.bool(obj.extended, buffer, bufferOffset);
    // Serialize message field [channel]
    bufferOffset = _serializer.uint32(obj.channel, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CANCommGoal
    let len;
    let data = new CANCommGoal(null);
    // Deserialize message field [can_id]
    data.can_id = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [data]
    data.data = _arrayDeserializer.uint8(buffer, bufferOffset, null)
    // Deserialize message field [dlc]
    data.dlc = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [extended]
    data.extended = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [channel]
    data.channel = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.data.length;
    return length + 14;
  }

  static datatype() {
    // Returns string type for a message object
    return 'maita_can_comm/CANCommGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2132a7b42d5791ec0695a2dd6adc00dc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    uint32 can_id           # CAN帧ID
    uint8[] data            # CAN数据 (最多8字节)
    uint8 dlc               # 数据长度 (0-8)
    bool extended           # 是否使用扩展帧
    uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CANCommGoal(null);
    if (msg.can_id !== undefined) {
      resolved.can_id = msg.can_id;
    }
    else {
      resolved.can_id = 0
    }

    if (msg.data !== undefined) {
      resolved.data = msg.data;
    }
    else {
      resolved.data = []
    }

    if (msg.dlc !== undefined) {
      resolved.dlc = msg.dlc;
    }
    else {
      resolved.dlc = 0
    }

    if (msg.extended !== undefined) {
      resolved.extended = msg.extended;
    }
    else {
      resolved.extended = false
    }

    if (msg.channel !== undefined) {
      resolved.channel = msg.channel;
    }
    else {
      resolved.channel = 0
    }

    return resolved;
    }
};

module.exports = CANCommGoal;
