// Generated by gencpp from file communication/NetworkCommunication.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_NETWORKCOMMUNICATION_H
#define COMMUNICATION_MESSAGE_NETWORKCOMMUNICATION_H

#include <ros/service_traits.h>


#include <communication/NetworkCommunicationRequest.h>
#include <communication/NetworkCommunicationResponse.h>


namespace communication
{

struct NetworkCommunication
{

typedef NetworkCommunicationRequest Request;
typedef NetworkCommunicationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NetworkCommunication
} // namespace communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::communication::NetworkCommunication > {
  static const char* value()
  {
    return "1669b1e1911ecbb5ee2158c03f61fe58";
  }

  static const char* value(const ::communication::NetworkCommunication&) { return value(); }
};

template<>
struct DataType< ::communication::NetworkCommunication > {
  static const char* value()
  {
    return "communication/NetworkCommunication";
  }

  static const char* value(const ::communication::NetworkCommunication&) { return value(); }
};


// service_traits::MD5Sum< ::communication::NetworkCommunicationRequest> should match
// service_traits::MD5Sum< ::communication::NetworkCommunication >
template<>
struct MD5Sum< ::communication::NetworkCommunicationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::communication::NetworkCommunication >::value();
  }
  static const char* value(const ::communication::NetworkCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication::NetworkCommunicationRequest> should match
// service_traits::DataType< ::communication::NetworkCommunication >
template<>
struct DataType< ::communication::NetworkCommunicationRequest>
{
  static const char* value()
  {
    return DataType< ::communication::NetworkCommunication >::value();
  }
  static const char* value(const ::communication::NetworkCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::communication::NetworkCommunicationResponse> should match
// service_traits::MD5Sum< ::communication::NetworkCommunication >
template<>
struct MD5Sum< ::communication::NetworkCommunicationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::communication::NetworkCommunication >::value();
  }
  static const char* value(const ::communication::NetworkCommunicationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication::NetworkCommunicationResponse> should match
// service_traits::DataType< ::communication::NetworkCommunication >
template<>
struct DataType< ::communication::NetworkCommunicationResponse>
{
  static const char* value()
  {
    return DataType< ::communication::NetworkCommunication >::value();
  }
  static const char* value(const ::communication::NetworkCommunicationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMUNICATION_MESSAGE_NETWORKCOMMUNICATION_H
