// Generated by gencpp from file communication/SerialCommunicationRequest.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_SERIALCOMMUNICATIONREQUEST_H
#define COMMUNICATION_MESSAGE_SERIALCOMMUNICATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication
{
template <class ContainerAllocator>
struct SerialCommunicationRequest_
{
  typedef SerialCommunicationRequest_<ContainerAllocator> Type;

  SerialCommunicationRequest_()
    : port()
    , baud_rate(0)
    , data()  {
    }
  SerialCommunicationRequest_(const ContainerAllocator& _alloc)
    : port(_alloc)
    , baud_rate(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _port_type;
  _port_type port;

   typedef int32_t _baud_rate_type;
  _baud_rate_type baud_rate;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::communication::SerialCommunicationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication::SerialCommunicationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialCommunicationRequest_

typedef ::communication::SerialCommunicationRequest_<std::allocator<void> > SerialCommunicationRequest;

typedef boost::shared_ptr< ::communication::SerialCommunicationRequest > SerialCommunicationRequestPtr;
typedef boost::shared_ptr< ::communication::SerialCommunicationRequest const> SerialCommunicationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication::SerialCommunicationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication::SerialCommunicationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication::SerialCommunicationRequest_<ContainerAllocator1> & lhs, const ::communication::SerialCommunicationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.baud_rate == rhs.baud_rate &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication::SerialCommunicationRequest_<ContainerAllocator1> & lhs, const ::communication::SerialCommunicationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication::SerialCommunicationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication::SerialCommunicationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication::SerialCommunicationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61d51af2822cefca2ebfa05aada10798";
  }

  static const char* value(const ::communication::SerialCommunicationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61d51af2822cefcaULL;
  static const uint64_t static_value2 = 0x2ebfa05aada10798ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication/SerialCommunicationRequest";
  }

  static const char* value(const ::communication::SerialCommunicationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string port\n"
"int32 baud_rate\n"
"string data\n"
;
  }

  static const char* value(const ::communication::SerialCommunicationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.baud_rate);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialCommunicationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication::SerialCommunicationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication::SerialCommunicationRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "port: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.port);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baud_rate: ";
    Printer<int32_t>::stream(s, indent + "  ", v.baud_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_MESSAGE_SERIALCOMMUNICATIONREQUEST_H
