// Generated by gencpp from file communication/SerialCommunication.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_MESSAGE_SERIALCOMMUNICATION_H
#define COMMUNICATION_MESSAGE_SERIALCOMMUNICATION_H

#include <ros/service_traits.h>


#include <communication/SerialCommunicationRequest.h>
#include <communication/SerialCommunicationResponse.h>


namespace communication
{

struct SerialCommunication
{

typedef SerialCommunicationRequest Request;
typedef SerialCommunicationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialCommunication
} // namespace communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::communication::SerialCommunication > {
  static const char* value()
  {
    return "463ba1f6ee8cee968834e03f974654f4";
  }

  static const char* value(const ::communication::SerialCommunication&) { return value(); }
};

template<>
struct DataType< ::communication::SerialCommunication > {
  static const char* value()
  {
    return "communication/SerialCommunication";
  }

  static const char* value(const ::communication::SerialCommunication&) { return value(); }
};


// service_traits::MD5Sum< ::communication::SerialCommunicationRequest> should match
// service_traits::MD5Sum< ::communication::SerialCommunication >
template<>
struct MD5Sum< ::communication::SerialCommunicationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::communication::SerialCommunication >::value();
  }
  static const char* value(const ::communication::SerialCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication::SerialCommunicationRequest> should match
// service_traits::DataType< ::communication::SerialCommunication >
template<>
struct DataType< ::communication::SerialCommunicationRequest>
{
  static const char* value()
  {
    return DataType< ::communication::SerialCommunication >::value();
  }
  static const char* value(const ::communication::SerialCommunicationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::communication::SerialCommunicationResponse> should match
// service_traits::MD5Sum< ::communication::SerialCommunication >
template<>
struct MD5Sum< ::communication::SerialCommunicationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::communication::SerialCommunication >::value();
  }
  static const char* value(const ::communication::SerialCommunicationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::communication::SerialCommunicationResponse> should match
// service_traits::DataType< ::communication::SerialCommunication >
template<>
struct DataType< ::communication::SerialCommunicationResponse>
{
  static const char* value()
  {
    return DataType< ::communication::SerialCommunication >::value();
  }
  static const char* value(const ::communication::SerialCommunicationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMUNICATION_MESSAGE_SERIALCOMMUNICATION_H
