; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude GPIOInterruptResult.msg.html

(cl:defclass <GPIOInterruptResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (interrupt_count
    :reader interrupt_count
    :initarg :interrupt_count
    :type cl:integer
    :initform 0))
)

(cl:defclass GPIOInterruptResult (<GPIOInterruptResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GPIOInterruptResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GPIOInterruptResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<GPIOInterruptResult> is deprecated: use my_action_pkg-msg:GPIOInterruptResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <GPIOInterruptResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:success-val is deprecated.  Use my_action_pkg-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'interrupt_count-val :lambda-list '(m))
(cl:defmethod interrupt_count-val ((m <GPIOInterruptResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:interrupt_count-val is deprecated.  Use my_action_pkg-msg:interrupt_count instead.")
  (interrupt_count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GPIOInterruptResult>) ostream)
  "Serializes a message object of type '<GPIOInterruptResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'interrupt_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'interrupt_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'interrupt_count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'interrupt_count)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GPIOInterruptResult>) istream)
  "Deserializes a message object of type '<GPIOInterruptResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'interrupt_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'interrupt_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'interrupt_count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'interrupt_count)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GPIOInterruptResult>)))
  "Returns string type for a message object of type '<GPIOInterruptResult>"
  "my_action_pkg/GPIOInterruptResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GPIOInterruptResult)))
  "Returns string type for a message object of type 'GPIOInterruptResult"
  "my_action_pkg/GPIOInterruptResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GPIOInterruptResult>)))
  "Returns md5sum for a message object of type '<GPIOInterruptResult>"
  "ec72f496a1eb54169abd0fa54232c20d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GPIOInterruptResult)))
  "Returns md5sum for a message object of type 'GPIOInterruptResult"
  "ec72f496a1eb54169abd0fa54232c20d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GPIOInterruptResult>)))
  "Returns full string definition for message of type '<GPIOInterruptResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool success               # 操作是否成功~%uint32 interrupt_count     # 检测到的中断次数~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GPIOInterruptResult)))
  "Returns full string definition for message of type 'GPIOInterruptResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool success               # 操作是否成功~%uint32 interrupt_count     # 检测到的中断次数~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GPIOInterruptResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GPIOInterruptResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GPIOInterruptResult
    (cl:cons ':success (success msg))
    (cl:cons ':interrupt_count (interrupt_count msg))
))
