; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude GPIOInterruptActionGoal.msg.html

(cl:defclass <GPIOInterruptActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type my_action_pkg-msg:GPIOInterruptGoal
    :initform (cl:make-instance 'my_action_pkg-msg:GPIOInterruptGoal)))
)

(cl:defclass GPIOInterruptActionGoal (<GPIOInterruptActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GPIOInterruptActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GPIOInterruptActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<GPIOInterruptActionGoal> is deprecated: use my_action_pkg-msg:GPIOInterruptActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <GPIOInterruptActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:header-val is deprecated.  Use my_action_pkg-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <GPIOInterruptActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:goal_id-val is deprecated.  Use my_action_pkg-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <GPIOInterruptActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:goal-val is deprecated.  Use my_action_pkg-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GPIOInterruptActionGoal>) ostream)
  "Serializes a message object of type '<GPIOInterruptActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GPIOInterruptActionGoal>) istream)
  "Deserializes a message object of type '<GPIOInterruptActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GPIOInterruptActionGoal>)))
  "Returns string type for a message object of type '<GPIOInterruptActionGoal>"
  "my_action_pkg/GPIOInterruptActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GPIOInterruptActionGoal)))
  "Returns string type for a message object of type 'GPIOInterruptActionGoal"
  "my_action_pkg/GPIOInterruptActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GPIOInterruptActionGoal>)))
  "Returns md5sum for a message object of type '<GPIOInterruptActionGoal>"
  "4a932c744d15adda44c807ebda375080")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GPIOInterruptActionGoal)))
  "Returns md5sum for a message object of type 'GPIOInterruptActionGoal"
  "4a932c744d15adda44c807ebda375080")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GPIOInterruptActionGoal>)))
  "Returns full string definition for message of type '<GPIOInterruptActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%GPIOInterruptGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_action_pkg/GPIOInterruptGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 pin_number           # GPIO 引脚号 (BCM 编号)~%uint8 edge_mode            # 边沿模式: 0=上升沿, 1=下降沿, 2=双边沿~%uint8 debounce_ms          # 去抖动时间 (毫秒)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GPIOInterruptActionGoal)))
  "Returns full string definition for message of type 'GPIOInterruptActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%GPIOInterruptGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_action_pkg/GPIOInterruptGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 pin_number           # GPIO 引脚号 (BCM 编号)~%uint8 edge_mode            # 边沿模式: 0=上升沿, 1=下降沿, 2=双边沿~%uint8 debounce_ms          # 去抖动时间 (毫秒)~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GPIOInterruptActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GPIOInterruptActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GPIOInterruptActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
