; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude I2CCommGoal.msg.html

(cl:defclass <I2CCommGoal> (roslisp-msg-protocol:ros-message)
  ((device_address
    :reader device_address
    :initarg :device_address
    :type cl:fixnum
    :initform 0)
   (register_address
    :reader register_address
    :initarg :register_address
    :type cl:fixnum
    :initform 0)
   (data
    :reader data
    :initarg :data
    :type cl:fixnum
    :initform 0))
)

(cl:defclass I2CCommGoal (<I2CCommGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <I2CCommGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'I2CCommGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<I2CCommGoal> is deprecated: use my_action_pkg-msg:I2CCommGoal instead.")))

(cl:ensure-generic-function 'device_address-val :lambda-list '(m))
(cl:defmethod device_address-val ((m <I2CCommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:device_address-val is deprecated.  Use my_action_pkg-msg:device_address instead.")
  (device_address m))

(cl:ensure-generic-function 'register_address-val :lambda-list '(m))
(cl:defmethod register_address-val ((m <I2CCommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:register_address-val is deprecated.  Use my_action_pkg-msg:register_address instead.")
  (register_address m))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <I2CCommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:data-val is deprecated.  Use my_action_pkg-msg:data instead.")
  (data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <I2CCommGoal>) ostream)
  "Serializes a message object of type '<I2CCommGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'device_address)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'register_address)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'data)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <I2CCommGoal>) istream)
  "Deserializes a message object of type '<I2CCommGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'device_address)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'register_address)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'data)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<I2CCommGoal>)))
  "Returns string type for a message object of type '<I2CCommGoal>"
  "my_action_pkg/I2CCommGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'I2CCommGoal)))
  "Returns string type for a message object of type 'I2CCommGoal"
  "my_action_pkg/I2CCommGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<I2CCommGoal>)))
  "Returns md5sum for a message object of type '<I2CCommGoal>"
  "5307d7662b39c52c3410c655875d704e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'I2CCommGoal)))
  "Returns md5sum for a message object of type 'I2CCommGoal"
  "5307d7662b39c52c3410c655875d704e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<I2CCommGoal>)))
  "Returns full string definition for message of type '<I2CCommGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 device_address~%uint8 register_address~%uint8 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'I2CCommGoal)))
  "Returns full string definition for message of type 'I2CCommGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 device_address~%uint8 register_address~%uint8 data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <I2CCommGoal>))
  (cl:+ 0
     1
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <I2CCommGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'I2CCommGoal
    (cl:cons ':device_address (device_address msg))
    (cl:cons ':register_address (register_address msg))
    (cl:cons ':data (data msg))
))
