; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude I2CCommResult.msg.html

(cl:defclass <I2CCommResult> (roslisp-msg-protocol:ros-message)
  ((received_data
    :reader received_data
    :initarg :received_data
    :type cl:fixnum
    :initform 0)
   (success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass I2CCommResult (<I2CCommResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <I2CCommResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'I2CCommResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<I2CCommResult> is deprecated: use my_action_pkg-msg:I2CCommResult instead.")))

(cl:ensure-generic-function 'received_data-val :lambda-list '(m))
(cl:defmethod received_data-val ((m <I2CCommResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:received_data-val is deprecated.  Use my_action_pkg-msg:received_data instead.")
  (received_data m))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <I2CCommResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:success-val is deprecated.  Use my_action_pkg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <I2CCommResult>) ostream)
  "Serializes a message object of type '<I2CCommResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'received_data)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <I2CCommResult>) istream)
  "Deserializes a message object of type '<I2CCommResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'received_data)) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<I2CCommResult>)))
  "Returns string type for a message object of type '<I2CCommResult>"
  "my_action_pkg/I2CCommResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'I2CCommResult)))
  "Returns string type for a message object of type 'I2CCommResult"
  "my_action_pkg/I2CCommResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<I2CCommResult>)))
  "Returns md5sum for a message object of type '<I2CCommResult>"
  "11c802d86867e8a549e84539b445145b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'I2CCommResult)))
  "Returns md5sum for a message object of type 'I2CCommResult"
  "11c802d86867e8a549e84539b445145b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<I2CCommResult>)))
  "Returns full string definition for message of type '<I2CCommResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint8 received_data~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'I2CCommResult)))
  "Returns full string definition for message of type 'I2CCommResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%uint8 received_data~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <I2CCommResult>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <I2CCommResult>))
  "Converts a ROS message object to a list"
  (cl:list 'I2CCommResult
    (cl:cons ':received_data (received_data msg))
    (cl:cons ':success (success msg))
))
