; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude I2CCommFeedback.msg.html

(cl:defclass <I2CCommFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass I2CCommFeedback (<I2CCommFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <I2CCommFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'I2CCommFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<I2CCommFeedback> is deprecated: use my_action_pkg-msg:I2CCommFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <I2CCommFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:status-val is deprecated.  Use my_action_pkg-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <I2CCommFeedback>) ostream)
  "Serializes a message object of type '<I2CCommFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <I2CCommFeedback>) istream)
  "Deserializes a message object of type '<I2CCommFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<I2CCommFeedback>)))
  "Returns string type for a message object of type '<I2CCommFeedback>"
  "my_action_pkg/I2CCommFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'I2CCommFeedback)))
  "Returns string type for a message object of type 'I2CCommFeedback"
  "my_action_pkg/I2CCommFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<I2CCommFeedback>)))
  "Returns md5sum for a message object of type '<I2CCommFeedback>"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'I2CCommFeedback)))
  "Returns md5sum for a message object of type 'I2CCommFeedback"
  "da740a2c07d1e6cb851fc1b477c8705a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<I2CCommFeedback>)))
  "Returns full string definition for message of type '<I2CCommFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'I2CCommFeedback)))
  "Returns full string definition for message of type 'I2CCommFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String status~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <I2CCommFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <I2CCommFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'I2CCommFeedback
    (cl:cons ':status (status msg))
))
