; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SerialCommGoal.msg.html

(cl:defclass <SerialCommGoal> (roslisp-msg-protocol:ros-message)
  ((data
    :reader data
    :initarg :data
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass SerialCommGoal (<SerialCommGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SerialCommGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SerialCommGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SerialCommGoal> is deprecated: use my_action_pkg-msg:SerialCommGoal instead.")))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <SerialCommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:data-val is deprecated.  Use my_action_pkg-msg:data instead.")
  (data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SerialCommGoal>) ostream)
  "Serializes a message object of type '<SerialCommGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'data) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SerialCommGoal>) istream)
  "Deserializes a message object of type '<SerialCommGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'data) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SerialCommGoal>)))
  "Returns string type for a message object of type '<SerialCommGoal>"
  "my_action_pkg/SerialCommGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SerialCommGoal)))
  "Returns string type for a message object of type 'SerialCommGoal"
  "my_action_pkg/SerialCommGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SerialCommGoal>)))
  "Returns md5sum for a message object of type '<SerialCommGoal>"
  "131c7b16e90d7646b67a1c83cd590279")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SerialCommGoal)))
  "Returns md5sum for a message object of type 'SerialCommGoal"
  "131c7b16e90d7646b67a1c83cd590279")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SerialCommGoal>)))
  "Returns full string definition for message of type '<SerialCommGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%std_msgs/String data~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SerialCommGoal)))
  "Returns full string definition for message of type 'SerialCommGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%std_msgs/String data~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SerialCommGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'data))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SerialCommGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SerialCommGoal
    (cl:cons ':data (data msg))
))
