; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SerialCommFeedback.msg.html

(cl:defclass <SerialCommFeedback> (roslisp-msg-protocol:ros-message)
  ((partial_data
    :reader partial_data
    :initarg :partial_data
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass SerialCommFeedback (<SerialCommFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SerialCommFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SerialCommFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SerialCommFeedback> is deprecated: use my_action_pkg-msg:SerialCommFeedback instead.")))

(cl:ensure-generic-function 'partial_data-val :lambda-list '(m))
(cl:defmethod partial_data-val ((m <SerialCommFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:partial_data-val is deprecated.  Use my_action_pkg-msg:partial_data instead.")
  (partial_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SerialCommFeedback>) ostream)
  "Serializes a message object of type '<SerialCommFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'partial_data) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SerialCommFeedback>) istream)
  "Deserializes a message object of type '<SerialCommFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'partial_data) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SerialCommFeedback>)))
  "Returns string type for a message object of type '<SerialCommFeedback>"
  "my_action_pkg/SerialCommFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SerialCommFeedback)))
  "Returns string type for a message object of type 'SerialCommFeedback"
  "my_action_pkg/SerialCommFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SerialCommFeedback>)))
  "Returns md5sum for a message object of type '<SerialCommFeedback>"
  "547b9faab8ee672f68a3e150a5914059")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SerialCommFeedback)))
  "Returns md5sum for a message object of type 'SerialCommFeedback"
  "547b9faab8ee672f68a3e150a5914059")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SerialCommFeedback>)))
  "Returns full string definition for message of type '<SerialCommFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String partial_data~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SerialCommFeedback)))
  "Returns full string definition for message of type 'SerialCommFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String partial_data~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SerialCommFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'partial_data))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SerialCommFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SerialCommFeedback
    (cl:cons ':partial_data (partial_data msg))
))
