; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SerialCommResult.msg.html

(cl:defclass <SerialCommResult> (roslisp-msg-protocol:ros-message)
  ((received_data
    :reader received_data
    :initarg :received_data
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String))
   (success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SerialCommResult (<SerialCommResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SerialCommResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SerialCommResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SerialCommResult> is deprecated: use my_action_pkg-msg:SerialCommResult instead.")))

(cl:ensure-generic-function 'received_data-val :lambda-list '(m))
(cl:defmethod received_data-val ((m <SerialCommResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:received_data-val is deprecated.  Use my_action_pkg-msg:received_data instead.")
  (received_data m))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <SerialCommResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:success-val is deprecated.  Use my_action_pkg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SerialCommResult>) ostream)
  "Serializes a message object of type '<SerialCommResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'received_data) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SerialCommResult>) istream)
  "Deserializes a message object of type '<SerialCommResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'received_data) istream)
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SerialCommResult>)))
  "Returns string type for a message object of type '<SerialCommResult>"
  "my_action_pkg/SerialCommResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SerialCommResult)))
  "Returns string type for a message object of type 'SerialCommResult"
  "my_action_pkg/SerialCommResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SerialCommResult>)))
  "Returns md5sum for a message object of type '<SerialCommResult>"
  "62edef80754232488b116d882f60ca55")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SerialCommResult)))
  "Returns md5sum for a message object of type 'SerialCommResult"
  "62edef80754232488b116d882f60ca55")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SerialCommResult>)))
  "Returns full string definition for message of type '<SerialCommResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%std_msgs/String received_data~%bool success~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SerialCommResult)))
  "Returns full string definition for message of type 'SerialCommResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%std_msgs/String received_data~%bool success~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SerialCommResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'received_data))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SerialCommResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SerialCommResult
    (cl:cons ':received_data (received_data msg))
    (cl:cons ':success (success msg))
))
