; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SPICommGoal.msg.html

(cl:defclass <SPICommGoal> (roslisp-msg-protocol:ros-message)
  ((spi_bus
    :reader spi_bus
    :initarg :spi_bus
    :type cl:fixnum
    :initform 0)
   (device_address
    :reader device_address
    :initarg :device_address
    :type cl:fixnum
    :initform 0)
   (write_data
    :reader write_data
    :initarg :write_data
    :type cl:fixnum
    :initform 0)
   (read_after_write
    :reader read_after_write
    :initarg :read_after_write
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SPICommGoal (<SPICommGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SPICommGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SPICommGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SPICommGoal> is deprecated: use my_action_pkg-msg:SPICommGoal instead.")))

(cl:ensure-generic-function 'spi_bus-val :lambda-list '(m))
(cl:defmethod spi_bus-val ((m <SPICommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:spi_bus-val is deprecated.  Use my_action_pkg-msg:spi_bus instead.")
  (spi_bus m))

(cl:ensure-generic-function 'device_address-val :lambda-list '(m))
(cl:defmethod device_address-val ((m <SPICommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:device_address-val is deprecated.  Use my_action_pkg-msg:device_address instead.")
  (device_address m))

(cl:ensure-generic-function 'write_data-val :lambda-list '(m))
(cl:defmethod write_data-val ((m <SPICommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:write_data-val is deprecated.  Use my_action_pkg-msg:write_data instead.")
  (write_data m))

(cl:ensure-generic-function 'read_after_write-val :lambda-list '(m))
(cl:defmethod read_after_write-val ((m <SPICommGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:read_after_write-val is deprecated.  Use my_action_pkg-msg:read_after_write instead.")
  (read_after_write m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SPICommGoal>) ostream)
  "Serializes a message object of type '<SPICommGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'spi_bus)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'device_address)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'write_data)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'read_after_write) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SPICommGoal>) istream)
  "Deserializes a message object of type '<SPICommGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'spi_bus)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'device_address)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'write_data)) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'read_after_write) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SPICommGoal>)))
  "Returns string type for a message object of type '<SPICommGoal>"
  "my_action_pkg/SPICommGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SPICommGoal)))
  "Returns string type for a message object of type 'SPICommGoal"
  "my_action_pkg/SPICommGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SPICommGoal>)))
  "Returns md5sum for a message object of type '<SPICommGoal>"
  "b1910c59826c3c7eab39b7d347267a4a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SPICommGoal)))
  "Returns md5sum for a message object of type 'SPICommGoal"
  "b1910c59826c3c7eab39b7d347267a4a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SPICommGoal>)))
  "Returns full string definition for message of type '<SPICommGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 spi_bus              # SPI 总线编号 (0, 1, 2)~%uint8 device_address       # 设备地址 (片选线编号)~%uint8 write_data           # 要写入的数据 (1字节)~%bool read_after_write      # 写入后是否读取~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SPICommGoal)))
  "Returns full string definition for message of type 'SPICommGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 spi_bus              # SPI 总线编号 (0, 1, 2)~%uint8 device_address       # 设备地址 (片选线编号)~%uint8 write_data           # 要写入的数据 (1字节)~%bool read_after_write      # 写入后是否读取~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SPICommGoal>))
  (cl:+ 0
     1
     1
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SPICommGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SPICommGoal
    (cl:cons ':spi_bus (spi_bus msg))
    (cl:cons ':device_address (device_address msg))
    (cl:cons ':write_data (write_data msg))
    (cl:cons ':read_after_write (read_after_write msg))
))
