; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SPICommActionGoal.msg.html

(cl:defclass <SPICommActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type my_action_pkg-msg:SPICommGoal
    :initform (cl:make-instance 'my_action_pkg-msg:SPICommGoal)))
)

(cl:defclass SPICommActionGoal (<SPICommActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SPICommActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SPICommActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SPICommActionGoal> is deprecated: use my_action_pkg-msg:SPICommActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <SPICommActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:header-val is deprecated.  Use my_action_pkg-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <SPICommActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:goal_id-val is deprecated.  Use my_action_pkg-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <SPICommActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:goal-val is deprecated.  Use my_action_pkg-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SPICommActionGoal>) ostream)
  "Serializes a message object of type '<SPICommActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SPICommActionGoal>) istream)
  "Deserializes a message object of type '<SPICommActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SPICommActionGoal>)))
  "Returns string type for a message object of type '<SPICommActionGoal>"
  "my_action_pkg/SPICommActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SPICommActionGoal)))
  "Returns string type for a message object of type 'SPICommActionGoal"
  "my_action_pkg/SPICommActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SPICommActionGoal>)))
  "Returns md5sum for a message object of type '<SPICommActionGoal>"
  "3015b379c2f687870c5d5f691bcd901b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SPICommActionGoal)))
  "Returns md5sum for a message object of type 'SPICommActionGoal"
  "3015b379c2f687870c5d5f691bcd901b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SPICommActionGoal>)))
  "Returns full string definition for message of type '<SPICommActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SPICommGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_action_pkg/SPICommGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 spi_bus              # SPI 总线编号 (0, 1, 2)~%uint8 device_address       # 设备地址 (片选线编号)~%uint8 write_data           # 要写入的数据 (1字节)~%bool read_after_write      # 写入后是否读取~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SPICommActionGoal)))
  "Returns full string definition for message of type 'SPICommActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SPICommGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_action_pkg/SPICommGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint8 spi_bus              # SPI 总线编号 (0, 1, 2)~%uint8 device_address       # 设备地址 (片选线编号)~%uint8 write_data           # 要写入的数据 (1字节)~%bool read_after_write      # 写入后是否读取~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SPICommActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SPICommActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SPICommActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
