; Auto-generated. Do not edit!


(cl:in-package my_action_pkg-msg)


;//! \htmlinclude SPICommFeedback.msg.html

(cl:defclass <SPICommFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String))
   (current_data
    :reader current_data
    :initarg :current_data
    :type cl:fixnum
    :initform 0))
)

(cl:defclass SPICommFeedback (<SPICommFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SPICommFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SPICommFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_pkg-msg:<SPICommFeedback> is deprecated: use my_action_pkg-msg:SPICommFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <SPICommFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:status-val is deprecated.  Use my_action_pkg-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'current_data-val :lambda-list '(m))
(cl:defmethod current_data-val ((m <SPICommFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_pkg-msg:current_data-val is deprecated.  Use my_action_pkg-msg:current_data instead.")
  (current_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SPICommFeedback>) ostream)
  "Serializes a message object of type '<SPICommFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'status) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'current_data)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SPICommFeedback>) istream)
  "Deserializes a message object of type '<SPICommFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'status) istream)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'current_data)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SPICommFeedback>)))
  "Returns string type for a message object of type '<SPICommFeedback>"
  "my_action_pkg/SPICommFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SPICommFeedback)))
  "Returns string type for a message object of type 'SPICommFeedback"
  "my_action_pkg/SPICommFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SPICommFeedback>)))
  "Returns md5sum for a message object of type '<SPICommFeedback>"
  "bf8e23de04e136de85afd80a9deeef55")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SPICommFeedback)))
  "Returns md5sum for a message object of type 'SPICommFeedback"
  "bf8e23de04e136de85afd80a9deeef55")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SPICommFeedback>)))
  "Returns full string definition for message of type '<SPICommFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String status    # 状态描述~%uint8 current_data         # 当前数据~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SPICommFeedback)))
  "Returns full string definition for message of type 'SPICommFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%std_msgs/String status    # 状态描述~%uint8 current_data         # 当前数据~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SPICommFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'status))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SPICommFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SPICommFeedback
    (cl:cons ':status (status msg))
    (cl:cons ':current_data (current_data msg))
))
