(cl:defpackage communication-srv
  (:use )
  (:export
   "NETWORKCOMMUNICATION"
   "<NETWORKCOMMUNICATION-REQUEST>"
   "NETWORKCOMMUNICATION-REQUEST"
   "<NETWORKCOMMUNICATION-RESPONSE>"
   "NETWORKCOMMUNICATION-RESPONSE"
   "SERIALCOMMUNICATION"
   "<SERIALCOMMUNICATION-REQUEST>"
   "SERIALCOMMUNICATION-REQUEST"
   "<SERIALCOMMUNICATION-RESPONSE>"
   "SERIALCOMMUNICATION-RESPONSE"
  ))

