// Auto-generated. Do not edit!

// (in-package my_action_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GPIOInterruptGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.pin_number = null;
      this.edge_mode = null;
      this.debounce_ms = null;
    }
    else {
      if (initObj.hasOwnProperty('pin_number')) {
        this.pin_number = initObj.pin_number
      }
      else {
        this.pin_number = 0;
      }
      if (initObj.hasOwnProperty('edge_mode')) {
        this.edge_mode = initObj.edge_mode
      }
      else {
        this.edge_mode = 0;
      }
      if (initObj.hasOwnProperty('debounce_ms')) {
        this.debounce_ms = initObj.debounce_ms
      }
      else {
        this.debounce_ms = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GPIOInterruptGoal
    // Serialize message field [pin_number]
    bufferOffset = _serializer.uint8(obj.pin_number, buffer, bufferOffset);
    // Serialize message field [edge_mode]
    bufferOffset = _serializer.uint8(obj.edge_mode, buffer, bufferOffset);
    // Serialize message field [debounce_ms]
    bufferOffset = _serializer.uint8(obj.debounce_ms, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GPIOInterruptGoal
    let len;
    let data = new GPIOInterruptGoal(null);
    // Deserialize message field [pin_number]
    data.pin_number = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [edge_mode]
    data.edge_mode = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [debounce_ms]
    data.debounce_ms = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 3;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_action_pkg/GPIOInterruptGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '526f2c5b1223af593afee2a420a7c5fc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    uint8 pin_number           # GPIO 引脚号 (BCM 编号)
    uint8 edge_mode            # 边沿模式: 0=上升沿, 1=下降沿, 2=双边沿
    uint8 debounce_ms          # 去抖动时间 (毫秒)
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GPIOInterruptGoal(null);
    if (msg.pin_number !== undefined) {
      resolved.pin_number = msg.pin_number;
    }
    else {
      resolved.pin_number = 0
    }

    if (msg.edge_mode !== undefined) {
      resolved.edge_mode = msg.edge_mode;
    }
    else {
      resolved.edge_mode = 0
    }

    if (msg.debounce_ms !== undefined) {
      resolved.debounce_ms = msg.debounce_ms;
    }
    else {
      resolved.debounce_ms = 0
    }

    return resolved;
    }
};

module.exports = GPIOInterruptGoal;
