// Auto-generated. Do not edit!

// (in-package my_action_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class GPIOInterruptFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.event_type = null;
      this.timestamp = null;
      this.pin_level = null;
    }
    else {
      if (initObj.hasOwnProperty('event_type')) {
        this.event_type = initObj.event_type
      }
      else {
        this.event_type = new std_msgs.msg.String();
      }
      if (initObj.hasOwnProperty('timestamp')) {
        this.timestamp = initObj.timestamp
      }
      else {
        this.timestamp = 0;
      }
      if (initObj.hasOwnProperty('pin_level')) {
        this.pin_level = initObj.pin_level
      }
      else {
        this.pin_level = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GPIOInterruptFeedback
    // Serialize message field [event_type]
    bufferOffset = std_msgs.msg.String.serialize(obj.event_type, buffer, bufferOffset);
    // Serialize message field [timestamp]
    bufferOffset = _serializer.uint64(obj.timestamp, buffer, bufferOffset);
    // Serialize message field [pin_level]
    bufferOffset = _serializer.uint8(obj.pin_level, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GPIOInterruptFeedback
    let len;
    let data = new GPIOInterruptFeedback(null);
    // Deserialize message field [event_type]
    data.event_type = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    // Deserialize message field [timestamp]
    data.timestamp = _deserializer.uint64(buffer, bufferOffset);
    // Deserialize message field [pin_level]
    data.pin_level = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.event_type);
    return length + 9;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_action_pkg/GPIOInterruptFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '64e9176140a86f6f71cf8f42175b763f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback definition
    std_msgs/String event_type    # 事件类型: "rising", "falling", "level"
    uint64 timestamp              # 时间戳 (ns)
    uint8 pin_level               # GPIO 电平: 0=LOW, 1=HIGH
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GPIOInterruptFeedback(null);
    if (msg.event_type !== undefined) {
      resolved.event_type = std_msgs.msg.String.Resolve(msg.event_type)
    }
    else {
      resolved.event_type = new std_msgs.msg.String()
    }

    if (msg.timestamp !== undefined) {
      resolved.timestamp = msg.timestamp;
    }
    else {
      resolved.timestamp = 0
    }

    if (msg.pin_level !== undefined) {
      resolved.pin_level = msg.pin_level;
    }
    else {
      resolved.pin_level = 0
    }

    return resolved;
    }
};

module.exports = GPIOInterruptFeedback;
