// Auto-generated. Do not edit!

// (in-package my_action_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class SerialCommResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.received_data = null;
      this.success = null;
    }
    else {
      if (initObj.hasOwnProperty('received_data')) {
        this.received_data = initObj.received_data
      }
      else {
        this.received_data = new std_msgs.msg.String();
      }
      if (initObj.hasOwnProperty('success')) {
        this.success = initObj.success
      }
      else {
        this.success = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SerialCommResult
    // Serialize message field [received_data]
    bufferOffset = std_msgs.msg.String.serialize(obj.received_data, buffer, bufferOffset);
    // Serialize message field [success]
    bufferOffset = _serializer.bool(obj.success, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SerialCommResult
    let len;
    let data = new SerialCommResult(null);
    // Deserialize message field [received_data]
    data.received_data = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    // Deserialize message field [success]
    data.success = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.received_data);
    return length + 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_action_pkg/SerialCommResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '62edef80754232488b116d882f60ca55';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # result definition
    std_msgs/String received_data
    bool success
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SerialCommResult(null);
    if (msg.received_data !== undefined) {
      resolved.received_data = std_msgs.msg.String.Resolve(msg.received_data)
    }
    else {
      resolved.received_data = new std_msgs.msg.String()
    }

    if (msg.success !== undefined) {
      resolved.success = msg.success;
    }
    else {
      resolved.success = false
    }

    return resolved;
    }
};

module.exports = SerialCommResult;
