// Auto-generated. Do not edit!

// (in-package my_action_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SPICommGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.spi_bus = null;
      this.device_address = null;
      this.write_data = null;
      this.read_after_write = null;
    }
    else {
      if (initObj.hasOwnProperty('spi_bus')) {
        this.spi_bus = initObj.spi_bus
      }
      else {
        this.spi_bus = 0;
      }
      if (initObj.hasOwnProperty('device_address')) {
        this.device_address = initObj.device_address
      }
      else {
        this.device_address = 0;
      }
      if (initObj.hasOwnProperty('write_data')) {
        this.write_data = initObj.write_data
      }
      else {
        this.write_data = 0;
      }
      if (initObj.hasOwnProperty('read_after_write')) {
        this.read_after_write = initObj.read_after_write
      }
      else {
        this.read_after_write = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SPICommGoal
    // Serialize message field [spi_bus]
    bufferOffset = _serializer.uint8(obj.spi_bus, buffer, bufferOffset);
    // Serialize message field [device_address]
    bufferOffset = _serializer.uint8(obj.device_address, buffer, bufferOffset);
    // Serialize message field [write_data]
    bufferOffset = _serializer.uint8(obj.write_data, buffer, bufferOffset);
    // Serialize message field [read_after_write]
    bufferOffset = _serializer.bool(obj.read_after_write, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SPICommGoal
    let len;
    let data = new SPICommGoal(null);
    // Deserialize message field [spi_bus]
    data.spi_bus = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [device_address]
    data.device_address = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [write_data]
    data.write_data = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [read_after_write]
    data.read_after_write = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_action_pkg/SPICommGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b1910c59826c3c7eab39b7d347267a4a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    uint8 spi_bus              # SPI 总线编号 (0, 1, 2)
    uint8 device_address       # 设备地址 (片选线编号)
    uint8 write_data           # 要写入的数据 (1字节)
    bool read_after_write      # 写入后是否读取
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SPICommGoal(null);
    if (msg.spi_bus !== undefined) {
      resolved.spi_bus = msg.spi_bus;
    }
    else {
      resolved.spi_bus = 0
    }

    if (msg.device_address !== undefined) {
      resolved.device_address = msg.device_address;
    }
    else {
      resolved.device_address = 0
    }

    if (msg.write_data !== undefined) {
      resolved.write_data = msg.write_data;
    }
    else {
      resolved.write_data = 0
    }

    if (msg.read_after_write !== undefined) {
      resolved.read_after_write = msg.read_after_write;
    }
    else {
      resolved.read_after_write = false
    }

    return resolved;
    }
};

module.exports = SPICommGoal;
