; Auto-generated. Do not edit!


(cl:in-package maita_can_comm-msg)


;//! \htmlinclude CANConfigFeedback.msg.html

(cl:defclass <CANConfigFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform ""))
)

(cl:defclass CANConfigFeedback (<CANConfigFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CANConfigFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CANConfigFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name maita_can_comm-msg:<CANConfigFeedback> is deprecated: use maita_can_comm-msg:CANConfigFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <CANConfigFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader maita_can_comm-msg:status-val is deprecated.  Use maita_can_comm-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CANConfigFeedback>) ostream)
  "Serializes a message object of type '<CANConfigFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CANConfigFeedback>) istream)
  "Deserializes a message object of type '<CANConfigFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CANConfigFeedback>)))
  "Returns string type for a message object of type '<CANConfigFeedback>"
  "maita_can_comm/CANConfigFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CANConfigFeedback)))
  "Returns string type for a message object of type 'CANConfigFeedback"
  "maita_can_comm/CANConfigFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CANConfigFeedback>)))
  "Returns md5sum for a message object of type '<CANConfigFeedback>"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CANConfigFeedback)))
  "Returns md5sum for a message object of type 'CANConfigFeedback"
  "4fe5af303955c287688e7347e9b00278")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CANConfigFeedback>)))
  "Returns full string definition for message of type '<CANConfigFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%string status           # 配置进度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CANConfigFeedback)))
  "Returns full string definition for message of type 'CANConfigFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%string status           # 配置进度~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CANConfigFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CANConfigFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CANConfigFeedback
    (cl:cons ':status (status msg))
))
