; Auto-generated. Do not edit!


(cl:in-package maita_can_comm-msg)


;//! \htmlinclude CANFilterActionGoal.msg.html

(cl:defclass <CANFilterActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type maita_can_comm-msg:CANFilterGoal
    :initform (cl:make-instance 'maita_can_comm-msg:CANFilterGoal)))
)

(cl:defclass CANFilterActionGoal (<CANFilterActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CANFilterActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CANFilterActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name maita_can_comm-msg:<CANFilterActionGoal> is deprecated: use maita_can_comm-msg:CANFilterActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <CANFilterActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader maita_can_comm-msg:header-val is deprecated.  Use maita_can_comm-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <CANFilterActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader maita_can_comm-msg:goal_id-val is deprecated.  Use maita_can_comm-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <CANFilterActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader maita_can_comm-msg:goal-val is deprecated.  Use maita_can_comm-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CANFilterActionGoal>) ostream)
  "Serializes a message object of type '<CANFilterActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CANFilterActionGoal>) istream)
  "Deserializes a message object of type '<CANFilterActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CANFilterActionGoal>)))
  "Returns string type for a message object of type '<CANFilterActionGoal>"
  "maita_can_comm/CANFilterActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CANFilterActionGoal)))
  "Returns string type for a message object of type 'CANFilterActionGoal"
  "maita_can_comm/CANFilterActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CANFilterActionGoal>)))
  "Returns md5sum for a message object of type '<CANFilterActionGoal>"
  "52b13f6e3e1ae1562345f1c71c4e28fc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CANFilterActionGoal)))
  "Returns md5sum for a message object of type 'CANFilterActionGoal"
  "52b13f6e3e1ae1562345f1c71c4e28fc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CANFilterActionGoal>)))
  "Returns full string definition for message of type '<CANFilterActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CANFilterGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: maita_can_comm/CANFilterGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint32 channel          # CAN通道~%uint32 can_id           # CAN帧ID~%uint32 can_id_mask      # CAN帧ID掩码~%bool enable             # 启用过滤~%bool extended           # 扩展帧过滤~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CANFilterActionGoal)))
  "Returns full string definition for message of type 'CANFilterActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CANFilterGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: maita_can_comm/CANFilterGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%uint32 channel          # CAN通道~%uint32 can_id           # CAN帧ID~%uint32 can_id_mask      # CAN帧ID掩码~%bool enable             # 启用过滤~%bool extended           # 扩展帧过滤~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CANFilterActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CANFilterActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CANFilterActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
