# goal definition
uint32 can_id           # CAN帧ID
uint8[] data            # CAN数据 (最多8字节)
uint8 dlc               # 数据长度 (0-8)
bool extended           # 是否使用扩展帧
uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)
---
# result definition
bool success            # 发送是否成功
string message          # 结果消息
---
# feedback definition
string status           # 发送状态