# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_action_pkg/PWMOutputGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PWMOutputGoal(genpy.Message):
  _md5sum = "1ff9352c3095a80174b88fcd113a603a"
  _type = "my_action_pkg/PWMOutputGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
uint8 pin_number           # GPIO 引脚号 (BCM 编号)
uint32 frequency           # PWM 频率
uint8 duty_cycle           # 占空比 0-100%
float32 duration           # 持续时间 (秒)
"""
  __slots__ = ['pin_number','frequency','duty_cycle','duration']
  _slot_types = ['uint8','uint32','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pin_number,frequency,duty_cycle,duration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PWMOutputGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pin_number is None:
        self.pin_number = 0
      if self.frequency is None:
        self.frequency = 0
      if self.duty_cycle is None:
        self.duty_cycle = 0
      if self.duration is None:
        self.duration = 0.
    else:
      self.pin_number = 0
      self.frequency = 0
      self.duty_cycle = 0
      self.duration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BIBf().pack(_x.pin_number, _x.frequency, _x.duty_cycle, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pin_number, _x.frequency, _x.duty_cycle, _x.duration,) = _get_struct_BIBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BIBf().pack(_x.pin_number, _x.frequency, _x.duty_cycle, _x.duration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.pin_number, _x.frequency, _x.duty_cycle, _x.duration,) = _get_struct_BIBf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BIBf = None
def _get_struct_BIBf():
    global _struct_BIBf
    if _struct_BIBf is None:
        _struct_BIBf = struct.Struct("<BIBf")
    return _struct_BIBf
