# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_action_pkg/SPICommGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SPICommGoal(genpy.Message):
  _md5sum = "b1910c59826c3c7eab39b7d347267a4a"
  _type = "my_action_pkg/SPICommGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
uint8 spi_bus              # SPI 总线编号 (0, 1, 2)
uint8 device_address       # 设备地址 (片选线编号)
uint8 write_data           # 要写入的数据 (1字节)
bool read_after_write      # 写入后是否读取
"""
  __slots__ = ['spi_bus','device_address','write_data','read_after_write']
  _slot_types = ['uint8','uint8','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       spi_bus,device_address,write_data,read_after_write

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SPICommGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.spi_bus is None:
        self.spi_bus = 0
      if self.device_address is None:
        self.device_address = 0
      if self.write_data is None:
        self.write_data = 0
      if self.read_after_write is None:
        self.read_after_write = False
    else:
      self.spi_bus = 0
      self.device_address = 0
      self.write_data = 0
      self.read_after_write = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.spi_bus, _x.device_address, _x.write_data, _x.read_after_write))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.spi_bus, _x.device_address, _x.write_data, _x.read_after_write,) = _get_struct_4B().unpack(str[start:end])
      self.read_after_write = bool(self.read_after_write)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.spi_bus, _x.device_address, _x.write_data, _x.read_after_write))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.spi_bus, _x.device_address, _x.write_data, _x.read_after_write,) = _get_struct_4B().unpack(str[start:end])
      self.read_after_write = bool(self.read_after_write)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
