# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maita_can_comm/CANConfigGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CANConfigGoal(genpy.Message):
  _md5sum = "3dc91cac39863340c8f462fe7adc795f"
  _type = "maita_can_comm/CANConfigGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)
uint32 baudrate         # 波特率 (如: 500000)
bool enable_loopback    # 启用回环模式
bool enable_timestamp   # 启用时间戳
"""
  __slots__ = ['channel','baudrate','enable_loopback','enable_timestamp']
  _slot_types = ['uint32','uint32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       channel,baudrate,enable_loopback,enable_timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CANConfigGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.channel is None:
        self.channel = 0
      if self.baudrate is None:
        self.baudrate = 0
      if self.enable_loopback is None:
        self.enable_loopback = False
      if self.enable_timestamp is None:
        self.enable_timestamp = False
    else:
      self.channel = 0
      self.baudrate = 0
      self.enable_loopback = False
      self.enable_timestamp = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I2B().pack(_x.channel, _x.baudrate, _x.enable_loopback, _x.enable_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.channel, _x.baudrate, _x.enable_loopback, _x.enable_timestamp,) = _get_struct_2I2B().unpack(str[start:end])
      self.enable_loopback = bool(self.enable_loopback)
      self.enable_timestamp = bool(self.enable_timestamp)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I2B().pack(_x.channel, _x.baudrate, _x.enable_loopback, _x.enable_timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.channel, _x.baudrate, _x.enable_loopback, _x.enable_timestamp,) = _get_struct_2I2B().unpack(str[start:end])
      self.enable_loopback = bool(self.enable_loopback)
      self.enable_timestamp = bool(self.enable_timestamp)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I2B = None
def _get_struct_2I2B():
    global _struct_2I2B
    if _struct_2I2B is None:
        _struct_2I2B = struct.Struct("<2I2B")
    return _struct_2I2B
