# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from maita_can_comm/CANFilterGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CANFilterGoal(genpy.Message):
  _md5sum = "22a569785d38997a7f1c42f98c5d9c20"
  _type = "maita_can_comm/CANFilterGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
uint32 channel          # CAN通道
uint32 can_id           # CAN帧ID
uint32 can_id_mask      # CAN帧ID掩码
bool enable             # 启用过滤
bool extended           # 扩展帧过滤
"""
  __slots__ = ['channel','can_id','can_id_mask','enable','extended']
  _slot_types = ['uint32','uint32','uint32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       channel,can_id,can_id_mask,enable,extended

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CANFilterGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.channel is None:
        self.channel = 0
      if self.can_id is None:
        self.can_id = 0
      if self.can_id_mask is None:
        self.can_id_mask = 0
      if self.enable is None:
        self.enable = False
      if self.extended is None:
        self.extended = False
    else:
      self.channel = 0
      self.can_id = 0
      self.can_id_mask = 0
      self.enable = False
      self.extended = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I2B().pack(_x.channel, _x.can_id, _x.can_id_mask, _x.enable, _x.extended))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.channel, _x.can_id, _x.can_id_mask, _x.enable, _x.extended,) = _get_struct_3I2B().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.extended = bool(self.extended)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I2B().pack(_x.channel, _x.can_id, _x.can_id_mask, _x.enable, _x.extended))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 14
      (_x.channel, _x.can_id, _x.can_id_mask, _x.enable, _x.extended,) = _get_struct_3I2B().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.extended = bool(self.extended)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I2B = None
def _get_struct_3I2B():
    global _struct_3I2B
    if _struct_3I2B is None:
        _struct_3I2B = struct.Struct("<3I2B")
    return _struct_3I2B
