#!/bin/bash

echo "========================================"
echo "  Jetson Nano 40引脚GPIO分布查询工具"
echo "========================================"
echo ""

cd /home/jetson/Desktop/Jetson_Nano/ROS_Project
source devel/setup.bash

echo "【Jetson Nano 40引脚GPIO完整分布】"
echo ""
echo "引脚号 | 功能类型 | 说明"
echo "------|---------|------"
echo "  1   | 电源     | 3.3V"
echo "  2   | 电源     | 5V"
echo "  3   | GPIO     | GPIO2 (SDA1)"
echo "  4   | 电源     | 5V"
echo "  5   | GPIO     | GPIO3 (SCL1)"
echo "   6   | 地       | GND"
echo "  7   | GPIO     | GPIO4 (GPCLK0) - 通用IO优先推荐"
echo "  8   | GPIO     | GPIO14 (TXD0) - UART TX"
echo "   9   | 地       | GND"
echo " 10  | GPIO     | GPIO15 (RXD0) - UART RX"
echo " 11  | GPIO     | GPIO17 (GEN0) - 通用IO优先推荐"
echo " 12  | GPIO     | GPIO18 (GEN1) - PWM支持"
echo "  13  | GPIO     | GPIO27 (GEN2) - 通用IO优先推荐"
echo "  14  | 地       | GND"
echo "  15  | GPIO     | GPIO22 (GEN3) - 通用IO优先推荐"
echo "  16  | GPIO     | GPIO23 (GEN4) - 通用IO优先推荐"
echo "  17  | 电源     | 3.3V"
echo "  18  | GPIO     | GPIO24 (GEN5) - PWM支持"
echo "  19  | GPIO     | GPIO10 (MOSI) - SPI"
echo "  20  | 地       | GND"
echo " 21  | GPIO     | GPIO9 (MISO) - SPI - 通用IO优先推荐"
echo "  22  | GPIO     | GPIO25 (MOSI) - SPI"
echo " 23  | GPIO     | GPIO11 (SCLK) - SPI"
echo "  | GPIO8 (CE0) - SPI - 通用IO优先推荐"
echo "  25  | 地       | GND"
echo "  26  | GPIO     | GPIO7 (CE1) - SPI - 通用IO优先推荐"
echo "  27  | ID_EEPROM | ID_SD (硬件ID)"
echo "  28  | GPIO     | ID_SC (硬件ID)"
echo " 29  | GPIO     | GPIO5 - 通用IO优先推荐"
echo "  30  | 地       | GND"
echo " 31  | GPIO     | GPIO6 - 通用IO优先推荐"
echo " 32  | GPIO     | GPIO12 - PWM支持"
echo " 33  | GPIO     | GPIO13 - PWM支持"
echo "  34  | 地       | GND"
echo "  35  | GPIO     | GPIO19 (MISO) - SPI"
echo " 36  | GPIO     | GPIO16 (CE2) - SPI"
echo " 37  | GPIO     | GPIO26 - 通用IO优先推荐"
echo " 38  | GPIO     | GPIO20 (SDA0) - I2C"
echo " 39  | 地       | GND"
echo "  40  | GPIO     | GPIO21 (SCL0) - I2C"

echo ""
echo "========================================"
echo "  GPIO使用建议"
echo "========================================"
echo ""

echo "【优先级1: 纯通用IO（推荐使用）】"
echo "  引脚 11: GPIO17 (GEN0) - 无特殊功能"
echo "  引脚 13: GPIO27 (GEN2) - 无特殊功能"
echo "  引脚 15: GPIO22 (GEN3) - 无特殊功能"
echo "  引脚 16: GPIO23 (GEN4) - 无特殊功能"
echo "  引脚 29: GPIO5 - 无特殊功能"
echo "  引脚 31: GPIO6 - 无特殊功能"
echo "  引脚 37: GPIO26 - 无特殊功能"

echo ""
echo "【优先级2: PWM支持引脚】"
echo "  引脚 12: GPIO18 (GEN1) - PWM支持"
echo "  引脚 18: GPIO24 (GEN5) - PWM支持"
echo "  引脚 32: GPIO12 - PWM支持"
echo "  引脚 33: GPIO13 - PWM支持"

echo ""
echo "【优先级3: 条件性通用IO】"
echo "  引脚 3, 5: I2C引脚（不使用I2C时可通用）"
echo "  引脚 38, 40: I2C引脚（不使用I2C时可通用）"
echo "  引脚 19, 21, 23, 24, 26, 35: SPI引脚（不使用SPI时可通用）"
echo "  引脚 8, 10: UART引脚（不使用UART时可通用）"

echo ""
echo "========================================"
echo "  GPIO状态读取方法"
echo "========================================"
echo ""

echo "【方法1: ROS话题接口（推荐）】"
echo "  1. 启动GPIO节点: roslaunch gpio_control universal_gpio.launch"
echo "  2. 读取GPIO状态: rostopic pub -1 /gpio/read std_msgs/Int32 \"data: 0\""
echo "  3. 监控GPIO状态: rostopic echo /gpio/state"
echo ""

echo "【方法2: 系统文件读取】"
echo "  # 查看GPIO方向"
echo "  cat /sys/class/gpio/gpio18/direction"
echo "  # 读取GPIO状态"
echo "  cat /sys/class/gpio/gpio18/value"
echo ""

echo "【方法3: Python直接读取】"
echo "  import Jetson.GPIO as GPIO"
echo "  GPIO.setmode(GPIO.BOARD)"
echo "  GPIO.setup(18, GPIO.IN)"
echo "  state = GPIO.input(18)"
echo "  print(f\"GPIO18状态: {state}\")"
echo ""

echo "【方法4: 快速查询当前GPIO状态】"
echo "  # 启动GPIO节点"
echo "  roslaunch gpio_control universal_gpio.launch &"
echo "  # 等待启动"
echo "  sleep 3"
echo "  # 读取所有GPIO状态"
echo "  rostopic echo /gpio/state"
echo ""

echo "========================================"
echo "  可用GPIO引脚汇总"
echo "========================================"
echo ""
echo "推荐使用（无冲突）: 11, 13, 15, 16, 29, 31, 37"
echo "PWM支持: 12, 18, 32, 33"
echo "I2C功能: 3, 5, 38, 40"
echo "SPI功能: 19, 21, 23, 24, 26, 35"
echo "UART功能: 8, 10"
echo ""
echo "电源地线（不可用）: 1, 2, 4, 6, 9, 14, 17, 20, 25, 30, 34, 39"
echo ""
echo "========================================"
echo "  快速使用示例"
echo "========================================"
echo ""
echo "1. 启动GPIO控制节点（终端1）:"
echo "   cd /home/jetson/Desktop/Jetson_Nano/ROS_Project"
echo "   source devel/setup.bash"
echo "   roslaunch gpio_control universal_gpio.launch"
echo ""
echo "2. 控制GPIO18（终端2）:"
echo "   cd /home/jetson/Desktop/Jetson_Nano/ROS_Project"
echo "   source devel/setup.bash"
echo "   rostopic pub -1 /gpio/write std_msgs/Int32 \"data: 0\""
echo ""
echo "3. 读取GPIO18状态:"
echo "   rostopic pub -1 /gpio/read std_msgs/Int32 \"data: 0\""
echo ""
echo "4. 监控所有GPIO状态:"
echo "   rostopic echo /gpio/state"
echo ""
echo "========================================"