// Generated by gencpp from file maita_can_comm/CANCommGoal.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANCOMMGOAL_H
#define MAITA_CAN_COMM_MESSAGE_CANCOMMGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANCommGoal_
{
  typedef CANCommGoal_<ContainerAllocator> Type;

  CANCommGoal_()
    : can_id(0)
    , data()
    , dlc(0)
    , extended(false)
    , channel(0)  {
    }
  CANCommGoal_(const ContainerAllocator& _alloc)
    : can_id(0)
    , data(_alloc)
    , dlc(0)
    , extended(false)
    , channel(0)  {
  (void)_alloc;
    }



   typedef uint32_t _can_id_type;
  _can_id_type can_id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _data_type;
  _data_type data;

   typedef uint8_t _dlc_type;
  _dlc_type dlc;

   typedef uint8_t _extended_type;
  _extended_type extended;

   typedef uint32_t _channel_type;
  _channel_type channel;





  typedef boost::shared_ptr< ::maita_can_comm::CANCommGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANCommGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CANCommGoal_

typedef ::maita_can_comm::CANCommGoal_<std::allocator<void> > CANCommGoal;

typedef boost::shared_ptr< ::maita_can_comm::CANCommGoal > CANCommGoalPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANCommGoal const> CANCommGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANCommGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANCommGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommGoal_<ContainerAllocator2> & rhs)
{
  return lhs.can_id == rhs.can_id &&
    lhs.data == rhs.data &&
    lhs.dlc == rhs.dlc &&
    lhs.extended == rhs.extended &&
    lhs.channel == rhs.channel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANCommGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2132a7b42d5791ec0695a2dd6adc00dc";
  }

  static const char* value(const ::maita_can_comm::CANCommGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2132a7b42d5791ecULL;
  static const uint64_t static_value2 = 0x0695a2dd6adc00dcULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANCommGoal";
  }

  static const char* value(const ::maita_can_comm::CANCommGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint32 can_id           # CAN帧ID\n"
"uint8[] data            # CAN数据 (最多8字节)\n"
"uint8 dlc               # 数据长度 (0-8)\n"
"bool extended           # 是否使用扩展帧\n"
"uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)\n"
;
  }

  static const char* value(const ::maita_can_comm::CANCommGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.can_id);
      stream.next(m.data);
      stream.next(m.dlc);
      stream.next(m.extended);
      stream.next(m.channel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANCommGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANCommGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "can_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.can_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    if (v.data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.data[i]);
    }
    if (v.data.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "dlc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dlc);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extended: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.extended);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "channel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.channel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANCOMMGOAL_H
