// Generated by gencpp from file maita_can_comm/CANConfigResult.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANCONFIGRESULT_H
#define MAITA_CAN_COMM_MESSAGE_CANCONFIGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANConfigResult_
{
  typedef CANConfigResult_<ContainerAllocator> Type;

  CANConfigResult_()
    : success(false)
    , message()
    , actual_baudrate(0)  {
    }
  CANConfigResult_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , actual_baudrate(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef uint32_t _actual_baudrate_type;
  _actual_baudrate_type actual_baudrate;





  typedef boost::shared_ptr< ::maita_can_comm::CANConfigResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANConfigResult_<ContainerAllocator> const> ConstPtr;

}; // struct CANConfigResult_

typedef ::maita_can_comm::CANConfigResult_<std::allocator<void> > CANConfigResult;

typedef boost::shared_ptr< ::maita_can_comm::CANConfigResult > CANConfigResultPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANConfigResult const> CANConfigResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANConfigResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANConfigResult_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANConfigResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.actual_baudrate == rhs.actual_baudrate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANConfigResult_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANConfigResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANConfigResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANConfigResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANConfigResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c39911db1f56df939c7bebecc05ae6c0";
  }

  static const char* value(const ::maita_can_comm::CANConfigResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc39911db1f56df93ULL;
  static const uint64_t static_value2 = 0x9c7bebecc05ae6c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANConfigResult";
  }

  static const char* value(const ::maita_can_comm::CANConfigResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool success            # 配置是否成功\n"
"string message          # 结果消息\n"
"uint32 actual_baudrate  # 实际波特率\n"
;
  }

  static const char* value(const ::maita_can_comm::CANConfigResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.actual_baudrate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANConfigResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANConfigResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANConfigResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "actual_baudrate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.actual_baudrate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANCONFIGRESULT_H
