// Generated by gencpp from file maita_can_comm/CANConfigGoal.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANCONFIGGOAL_H
#define MAITA_CAN_COMM_MESSAGE_CANCONFIGGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANConfigGoal_
{
  typedef CANConfigGoal_<ContainerAllocator> Type;

  CANConfigGoal_()
    : channel(0)
    , baudrate(0)
    , enable_loopback(false)
    , enable_timestamp(false)  {
    }
  CANConfigGoal_(const ContainerAllocator& _alloc)
    : channel(0)
    , baudrate(0)
    , enable_loopback(false)
    , enable_timestamp(false)  {
  (void)_alloc;
    }



   typedef uint32_t _channel_type;
  _channel_type channel;

   typedef uint32_t _baudrate_type;
  _baudrate_type baudrate;

   typedef uint8_t _enable_loopback_type;
  _enable_loopback_type enable_loopback;

   typedef uint8_t _enable_timestamp_type;
  _enable_timestamp_type enable_timestamp;





  typedef boost::shared_ptr< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CANConfigGoal_

typedef ::maita_can_comm::CANConfigGoal_<std::allocator<void> > CANConfigGoal;

typedef boost::shared_ptr< ::maita_can_comm::CANConfigGoal > CANConfigGoalPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANConfigGoal const> CANConfigGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANConfigGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANConfigGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANConfigGoal_<ContainerAllocator2> & rhs)
{
  return lhs.channel == rhs.channel &&
    lhs.baudrate == rhs.baudrate &&
    lhs.enable_loopback == rhs.enable_loopback &&
    lhs.enable_timestamp == rhs.enable_timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANConfigGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANConfigGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc91cac39863340c8f462fe7adc795f";
  }

  static const char* value(const ::maita_can_comm::CANConfigGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc91cac39863340ULL;
  static const uint64_t static_value2 = 0xc8f462fe7adc795fULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANConfigGoal";
  }

  static const char* value(const ::maita_can_comm::CANConfigGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)\n"
"uint32 baudrate         # 波特率 (如: 500000)\n"
"bool enable_loopback    # 启用回环模式\n"
"bool enable_timestamp   # 启用时间戳\n"
;
  }

  static const char* value(const ::maita_can_comm::CANConfigGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.baudrate);
      stream.next(m.enable_loopback);
      stream.next(m.enable_timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANConfigGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANConfigGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANConfigGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "channel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.channel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "baudrate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.baudrate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable_loopback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_loopback);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable_timestamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANCONFIGGOAL_H
