// Generated by gencpp from file maita_can_comm/CANCommFeedback.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANCOMMFEEDBACK_H
#define MAITA_CAN_COMM_MESSAGE_CANCOMMFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANCommFeedback_
{
  typedef CANCommFeedback_<ContainerAllocator> Type;

  CANCommFeedback_()
    : status()  {
    }
  CANCommFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CANCommFeedback_

typedef ::maita_can_comm::CANCommFeedback_<std::allocator<void> > CANCommFeedback;

typedef boost::shared_ptr< ::maita_can_comm::CANCommFeedback > CANCommFeedbackPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANCommFeedback const> CANCommFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANCommFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANCommFeedback_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANCommFeedback_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::maita_can_comm::CANCommFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANCommFeedback";
  }

  static const char* value(const ::maita_can_comm::CANCommFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"string status           # 发送状态\n"
;
  }

  static const char* value(const ::maita_can_comm::CANCommFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANCommFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANCommFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANCommFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANCOMMFEEDBACK_H
