// Generated by gencpp from file maita_can_comm/CANCommActionGoal.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANCOMMACTIONGOAL_H
#define MAITA_CAN_COMM_MESSAGE_CANCOMMACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <maita_can_comm/CANCommGoal.h>

namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANCommActionGoal_
{
  typedef CANCommActionGoal_<ContainerAllocator> Type;

  CANCommActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  CANCommActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::maita_can_comm::CANCommGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CANCommActionGoal_

typedef ::maita_can_comm::CANCommActionGoal_<std::allocator<void> > CANCommActionGoal;

typedef boost::shared_ptr< ::maita_can_comm::CANCommActionGoal > CANCommActionGoalPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANCommActionGoal const> CANCommActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4eb51d9c496e7539653d5216a85ece1";
  }

  static const char* value(const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4eb51d9c496e753ULL;
  static const uint64_t static_value2 = 0x9653d5216a85ece1ULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANCommActionGoal";
  }

  static const char* value(const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CANCommGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANCommGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint32 can_id           # CAN帧ID\n"
"uint8[] data            # CAN数据 (最多8字节)\n"
"uint8 dlc               # 数据长度 (0-8)\n"
"bool extended           # 是否使用扩展帧\n"
"uint32 channel          # CAN通道 (0=CAN0, 1=CAN1)\n"
;
  }

  static const char* value(const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANCommActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANCommActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANCommActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::maita_can_comm::CANCommGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANCOMMACTIONGOAL_H
