// Generated by gencpp from file maita_can_comm/CANFilterGoal.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANFILTERGOAL_H
#define MAITA_CAN_COMM_MESSAGE_CANFILTERGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANFilterGoal_
{
  typedef CANFilterGoal_<ContainerAllocator> Type;

  CANFilterGoal_()
    : channel(0)
    , can_id(0)
    , can_id_mask(0)
    , enable(false)
    , extended(false)  {
    }
  CANFilterGoal_(const ContainerAllocator& _alloc)
    : channel(0)
    , can_id(0)
    , can_id_mask(0)
    , enable(false)
    , extended(false)  {
  (void)_alloc;
    }



   typedef uint32_t _channel_type;
  _channel_type channel;

   typedef uint32_t _can_id_type;
  _can_id_type can_id;

   typedef uint32_t _can_id_mask_type;
  _can_id_mask_type can_id_mask;

   typedef uint8_t _enable_type;
  _enable_type enable;

   typedef uint8_t _extended_type;
  _extended_type extended;





  typedef boost::shared_ptr< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CANFilterGoal_

typedef ::maita_can_comm::CANFilterGoal_<std::allocator<void> > CANFilterGoal;

typedef boost::shared_ptr< ::maita_can_comm::CANFilterGoal > CANFilterGoalPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANFilterGoal const> CANFilterGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANFilterGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANFilterGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANFilterGoal_<ContainerAllocator2> & rhs)
{
  return lhs.channel == rhs.channel &&
    lhs.can_id == rhs.can_id &&
    lhs.can_id_mask == rhs.can_id_mask &&
    lhs.enable == rhs.enable &&
    lhs.extended == rhs.extended;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANFilterGoal_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANFilterGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22a569785d38997a7f1c42f98c5d9c20";
  }

  static const char* value(const ::maita_can_comm::CANFilterGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22a569785d38997aULL;
  static const uint64_t static_value2 = 0x7f1c42f98c5d9c20ULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANFilterGoal";
  }

  static const char* value(const ::maita_can_comm::CANFilterGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint32 channel          # CAN通道\n"
"uint32 can_id           # CAN帧ID\n"
"uint32 can_id_mask      # CAN帧ID掩码\n"
"bool enable             # 启用过滤\n"
"bool extended           # 扩展帧过滤\n"
;
  }

  static const char* value(const ::maita_can_comm::CANFilterGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.can_id);
      stream.next(m.can_id_mask);
      stream.next(m.enable);
      stream.next(m.extended);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANFilterGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANFilterGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANFilterGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "channel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.channel);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "can_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.can_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "can_id_mask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.can_id_mask);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "extended: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.extended);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANFILTERGOAL_H
