// Generated by gencpp from file maita_can_comm/CANFilterAction.msg
// DO NOT EDIT!


#ifndef MAITA_CAN_COMM_MESSAGE_CANFILTERACTION_H
#define MAITA_CAN_COMM_MESSAGE_CANFILTERACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <maita_can_comm/CANFilterActionGoal.h>
#include <maita_can_comm/CANFilterActionResult.h>
#include <maita_can_comm/CANFilterActionFeedback.h>

namespace maita_can_comm
{
template <class ContainerAllocator>
struct CANFilterAction_
{
  typedef CANFilterAction_<ContainerAllocator> Type;

  CANFilterAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  CANFilterAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::maita_can_comm::CANFilterActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::maita_can_comm::CANFilterActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::maita_can_comm::CANFilterActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::maita_can_comm::CANFilterAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::maita_can_comm::CANFilterAction_<ContainerAllocator> const> ConstPtr;

}; // struct CANFilterAction_

typedef ::maita_can_comm::CANFilterAction_<std::allocator<void> > CANFilterAction;

typedef boost::shared_ptr< ::maita_can_comm::CANFilterAction > CANFilterActionPtr;
typedef boost::shared_ptr< ::maita_can_comm::CANFilterAction const> CANFilterActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::maita_can_comm::CANFilterAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::maita_can_comm::CANFilterAction_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANFilterAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::maita_can_comm::CANFilterAction_<ContainerAllocator1> & lhs, const ::maita_can_comm::CANFilterAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace maita_can_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::maita_can_comm::CANFilterAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::maita_can_comm::CANFilterAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::maita_can_comm::CANFilterAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6650950d7ae5f543fa2f287a16889186";
  }

  static const char* value(const ::maita_can_comm::CANFilterAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6650950d7ae5f543ULL;
  static const uint64_t static_value2 = 0xfa2f287a16889186ULL;
};

template<class ContainerAllocator>
struct DataType< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "maita_can_comm/CANFilterAction";
  }

  static const char* value(const ::maita_can_comm::CANFilterAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"CANFilterActionGoal action_goal\n"
"CANFilterActionResult action_result\n"
"CANFilterActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"CANFilterGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint32 channel          # CAN通道\n"
"uint32 can_id           # CAN帧ID\n"
"uint32 can_id_mask      # CAN帧ID掩码\n"
"bool enable             # 启用过滤\n"
"bool extended           # 扩展帧过滤\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CANFilterResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool success            # 过滤器配置是否成功\n"
"string message          # 结果消息\n"
"uint8 filter_index      # 过滤器索引\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"CANFilterFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: maita_can_comm/CANFilterFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"string status           # 过滤器状态\n"
;
  }

  static const char* value(const ::maita_can_comm::CANFilterAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CANFilterAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::maita_can_comm::CANFilterAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::maita_can_comm::CANFilterAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::maita_can_comm::CANFilterActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::maita_can_comm::CANFilterActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::maita_can_comm::CANFilterActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAITA_CAN_COMM_MESSAGE_CANFILTERACTION_H
