// Generated by gencpp from file gpio_control/GPIOControl.msg
// DO NOT EDIT!


#ifndef GPIO_CONTROL_MESSAGE_GPIOCONTROL_H
#define GPIO_CONTROL_MESSAGE_GPIOCONTROL_H

#include <ros/service_traits.h>


#include <gpio_control/GPIOControlRequest.h>
#include <gpio_control/GPIOControlResponse.h>


namespace gpio_control
{

struct GPIOControl
{

typedef GPIOControlRequest Request;
typedef GPIOControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GPIOControl
} // namespace gpio_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gpio_control::GPIOControl > {
  static const char* value()
  {
    return "fb7e1816990c224213820b65098f630b";
  }

  static const char* value(const ::gpio_control::GPIOControl&) { return value(); }
};

template<>
struct DataType< ::gpio_control::GPIOControl > {
  static const char* value()
  {
    return "gpio_control/GPIOControl";
  }

  static const char* value(const ::gpio_control::GPIOControl&) { return value(); }
};


// service_traits::MD5Sum< ::gpio_control::GPIOControlRequest> should match
// service_traits::MD5Sum< ::gpio_control::GPIOControl >
template<>
struct MD5Sum< ::gpio_control::GPIOControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gpio_control::GPIOControl >::value();
  }
  static const char* value(const ::gpio_control::GPIOControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpio_control::GPIOControlRequest> should match
// service_traits::DataType< ::gpio_control::GPIOControl >
template<>
struct DataType< ::gpio_control::GPIOControlRequest>
{
  static const char* value()
  {
    return DataType< ::gpio_control::GPIOControl >::value();
  }
  static const char* value(const ::gpio_control::GPIOControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gpio_control::GPIOControlResponse> should match
// service_traits::MD5Sum< ::gpio_control::GPIOControl >
template<>
struct MD5Sum< ::gpio_control::GPIOControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gpio_control::GPIOControl >::value();
  }
  static const char* value(const ::gpio_control::GPIOControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gpio_control::GPIOControlResponse> should match
// service_traits::DataType< ::gpio_control::GPIOControl >
template<>
struct DataType< ::gpio_control::GPIOControlResponse>
{
  static const char* value()
  {
    return DataType< ::gpio_control::GPIOControl >::value();
  }
  static const char* value(const ::gpio_control::GPIOControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GPIO_CONTROL_MESSAGE_GPIOCONTROL_H
