// Generated by gencpp from file gpio_control/GPIOControlRequest.msg
// DO NOT EDIT!


#ifndef GPIO_CONTROL_MESSAGE_GPIOCONTROLREQUEST_H
#define GPIO_CONTROL_MESSAGE_GPIOCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gpio_control
{
template <class ContainerAllocator>
struct GPIOControlRequest_
{
  typedef GPIOControlRequest_<ContainerAllocator> Type;

  GPIOControlRequest_()
    : pin_number(0)
    , state(false)  {
    }
  GPIOControlRequest_(const ContainerAllocator& _alloc)
    : pin_number(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef int32_t _pin_number_type;
  _pin_number_type pin_number;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::gpio_control::GPIOControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpio_control::GPIOControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GPIOControlRequest_

typedef ::gpio_control::GPIOControlRequest_<std::allocator<void> > GPIOControlRequest;

typedef boost::shared_ptr< ::gpio_control::GPIOControlRequest > GPIOControlRequestPtr;
typedef boost::shared_ptr< ::gpio_control::GPIOControlRequest const> GPIOControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpio_control::GPIOControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gpio_control::GPIOControlRequest_<ContainerAllocator1> & lhs, const ::gpio_control::GPIOControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pin_number == rhs.pin_number &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gpio_control::GPIOControlRequest_<ContainerAllocator1> & lhs, const ::gpio_control::GPIOControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gpio_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpio_control::GPIOControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpio_control::GPIOControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpio_control::GPIOControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f77578e0604ac5172717ccda47ee0dc";
  }

  static const char* value(const ::gpio_control::GPIOControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f77578e0604ac51ULL;
  static const uint64_t static_value2 = 0x72717ccda47ee0dcULL;
};

template<class ContainerAllocator>
struct DataType< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpio_control/GPIOControlRequest";
  }

  static const char* value(const ::gpio_control::GPIOControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 pin_number\n"
"bool state\n"
;
  }

  static const char* value(const ::gpio_control::GPIOControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin_number);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPIOControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpio_control::GPIOControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpio_control::GPIOControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pin_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pin_number);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPIO_CONTROL_MESSAGE_GPIOCONTROLREQUEST_H
