// Generated by gencpp from file my_action_pkg/FibonacciFeedback.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_FIBONACCIFEEDBACK_H
#define MY_ACTION_PKG_MESSAGE_FIBONACCIFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_pkg
{
template <class ContainerAllocator>
struct FibonacciFeedback_
{
  typedef FibonacciFeedback_<ContainerAllocator> Type;

  FibonacciFeedback_()
    : partial_sequence()  {
    }
  FibonacciFeedback_(const ContainerAllocator& _alloc)
    : partial_sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _partial_sequence_type;
  _partial_sequence_type partial_sequence;





  typedef boost::shared_ptr< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FibonacciFeedback_

typedef ::my_action_pkg::FibonacciFeedback_<std::allocator<void> > FibonacciFeedback;

typedef boost::shared_ptr< ::my_action_pkg::FibonacciFeedback > FibonacciFeedbackPtr;
typedef boost::shared_ptr< ::my_action_pkg::FibonacciFeedback const> FibonacciFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.partial_sequence == rhs.partial_sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c324d8171fd53e3a9e11483af0517576";
  }

  static const char* value(const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc324d8171fd53e3aULL;
  static const uint64_t static_value2 = 0x9e11483af0517576ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/FibonacciFeedback";
  }

  static const char* value(const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"int32[] partial_sequence\n"
;
  }

  static const char* value(const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.partial_sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FibonacciFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::FibonacciFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::FibonacciFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "partial_sequence: ";
    if (v.partial_sequence.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.partial_sequence.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<int32_t>::stream(s, true ? std::string() : indent + "    ", v.partial_sequence[i]);
    }
    if (v.partial_sequence.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_FIBONACCIFEEDBACK_H
