// Generated by gencpp from file my_action_pkg/GPIOInterruptGoal.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTGOAL_H
#define MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_pkg
{
template <class ContainerAllocator>
struct GPIOInterruptGoal_
{
  typedef GPIOInterruptGoal_<ContainerAllocator> Type;

  GPIOInterruptGoal_()
    : pin_number(0)
    , edge_mode(0)
    , debounce_ms(0)  {
    }
  GPIOInterruptGoal_(const ContainerAllocator& _alloc)
    : pin_number(0)
    , edge_mode(0)
    , debounce_ms(0)  {
  (void)_alloc;
    }



   typedef uint8_t _pin_number_type;
  _pin_number_type pin_number;

   typedef uint8_t _edge_mode_type;
  _edge_mode_type edge_mode;

   typedef uint8_t _debounce_ms_type;
  _debounce_ms_type debounce_ms;





  typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GPIOInterruptGoal_

typedef ::my_action_pkg::GPIOInterruptGoal_<std::allocator<void> > GPIOInterruptGoal;

typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptGoal > GPIOInterruptGoalPtr;
typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptGoal const> GPIOInterruptGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator2> & rhs)
{
  return lhs.pin_number == rhs.pin_number &&
    lhs.edge_mode == rhs.edge_mode &&
    lhs.debounce_ms == rhs.debounce_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "526f2c5b1223af593afee2a420a7c5fc";
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x526f2c5b1223af59ULL;
  static const uint64_t static_value2 = 0x3afee2a420a7c5fcULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/GPIOInterruptGoal";
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint8 pin_number           # GPIO 引脚号 (BCM 编号)\n"
"uint8 edge_mode            # 边沿模式: 0=上升沿, 1=下降沿, 2=双边沿\n"
"uint8 debounce_ms          # 去抖动时间 (毫秒)\n"
;
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pin_number);
      stream.next(m.edge_mode);
      stream.next(m.debounce_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPIOInterruptGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::GPIOInterruptGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pin_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pin_number);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "edge_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.edge_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "debounce_ms: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.debounce_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTGOAL_H
