// Generated by gencpp from file my_action_pkg/GPIOInterruptResult.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTRESULT_H
#define MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_pkg
{
template <class ContainerAllocator>
struct GPIOInterruptResult_
{
  typedef GPIOInterruptResult_<ContainerAllocator> Type;

  GPIOInterruptResult_()
    : success(false)
    , interrupt_count(0)  {
    }
  GPIOInterruptResult_(const ContainerAllocator& _alloc)
    : success(false)
    , interrupt_count(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint32_t _interrupt_count_type;
  _interrupt_count_type interrupt_count;





  typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> const> ConstPtr;

}; // struct GPIOInterruptResult_

typedef ::my_action_pkg::GPIOInterruptResult_<std::allocator<void> > GPIOInterruptResult;

typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptResult > GPIOInterruptResultPtr;
typedef boost::shared_ptr< ::my_action_pkg::GPIOInterruptResult const> GPIOInterruptResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.interrupt_count == rhs.interrupt_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec72f496a1eb54169abd0fa54232c20d";
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec72f496a1eb5416ULL;
  static const uint64_t static_value2 = 0x9abd0fa54232c20dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/GPIOInterruptResult";
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool success               # 操作是否成功\n"
"uint32 interrupt_count     # 检测到的中断次数\n"
;
  }

  static const char* value(const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.interrupt_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPIOInterruptResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::GPIOInterruptResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "interrupt_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.interrupt_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_GPIOINTERRUPTRESULT_H
