// Generated by gencpp from file my_action_pkg/I2CCommResult.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_I2CCOMMRESULT_H
#define MY_ACTION_PKG_MESSAGE_I2CCOMMRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_pkg
{
template <class ContainerAllocator>
struct I2CCommResult_
{
  typedef I2CCommResult_<ContainerAllocator> Type;

  I2CCommResult_()
    : received_data(0)
    , success(false)  {
    }
  I2CCommResult_(const ContainerAllocator& _alloc)
    : received_data(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_data_type;
  _received_data_type received_data;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::my_action_pkg::I2CCommResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::I2CCommResult_<ContainerAllocator> const> ConstPtr;

}; // struct I2CCommResult_

typedef ::my_action_pkg::I2CCommResult_<std::allocator<void> > I2CCommResult;

typedef boost::shared_ptr< ::my_action_pkg::I2CCommResult > I2CCommResultPtr;
typedef boost::shared_ptr< ::my_action_pkg::I2CCommResult const> I2CCommResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::I2CCommResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::I2CCommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::I2CCommResult_<ContainerAllocator2> & rhs)
{
  return lhs.received_data == rhs.received_data &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::I2CCommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::I2CCommResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::I2CCommResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::I2CCommResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::I2CCommResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11c802d86867e8a549e84539b445145b";
  }

  static const char* value(const ::my_action_pkg::I2CCommResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11c802d86867e8a5ULL;
  static const uint64_t static_value2 = 0x49e84539b445145bULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/I2CCommResult";
  }

  static const char* value(const ::my_action_pkg::I2CCommResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"uint8 received_data\n"
"bool success\n"
;
  }

  static const char* value(const ::my_action_pkg::I2CCommResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received_data);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct I2CCommResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::I2CCommResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::I2CCommResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "received_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_I2CCOMMRESULT_H
