// Generated by gencpp from file my_action_pkg/I2CCommActionGoal.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_I2CCOMMACTIONGOAL_H
#define MY_ACTION_PKG_MESSAGE_I2CCOMMACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <my_action_pkg/I2CCommGoal.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct I2CCommActionGoal_
{
  typedef I2CCommActionGoal_<ContainerAllocator> Type;

  I2CCommActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  I2CCommActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::my_action_pkg::I2CCommGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct I2CCommActionGoal_

typedef ::my_action_pkg::I2CCommActionGoal_<std::allocator<void> > I2CCommActionGoal;

typedef boost::shared_ptr< ::my_action_pkg::I2CCommActionGoal > I2CCommActionGoalPtr;
typedef boost::shared_ptr< ::my_action_pkg::I2CCommActionGoal const> I2CCommActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50359faf0da32962c7fcfae4a180348e";
  }

  static const char* value(const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50359faf0da32962ULL;
  static const uint64_t static_value2 = 0xc7fcfae4a180348eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/I2CCommActionGoal";
  }

  static const char* value(const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"I2CCommGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/I2CCommGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"uint8 device_address\n"
"uint8 register_address\n"
"uint8 data\n"
;
  }

  static const char* value(const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct I2CCommActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::I2CCommActionGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal_id: ";
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "goal: ";
    Printer< ::my_action_pkg::I2CCommGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_I2CCOMMACTIONGOAL_H
