// Generated by gencpp from file my_action_pkg/SerialCommGoal.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SERIALCOMMGOAL_H
#define MY_ACTION_PKG_MESSAGE_SERIALCOMMGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct SerialCommGoal_
{
  typedef SerialCommGoal_<ContainerAllocator> Type;

  SerialCommGoal_()
    : data()  {
    }
  SerialCommGoal_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SerialCommGoal_

typedef ::my_action_pkg::SerialCommGoal_<std::allocator<void> > SerialCommGoal;

typedef boost::shared_ptr< ::my_action_pkg::SerialCommGoal > SerialCommGoalPtr;
typedef boost::shared_ptr< ::my_action_pkg::SerialCommGoal const> SerialCommGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SerialCommGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SerialCommGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommGoal_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SerialCommGoal_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "131c7b16e90d7646b67a1c83cd590279";
  }

  static const char* value(const ::my_action_pkg::SerialCommGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x131c7b16e90d7646ULL;
  static const uint64_t static_value2 = 0xb67a1c83cd590279ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SerialCommGoal";
  }

  static const char* value(const ::my_action_pkg::SerialCommGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"std_msgs/String data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::my_action_pkg::SerialCommGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialCommGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SerialCommGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SerialCommGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SERIALCOMMGOAL_H
