// Generated by gencpp from file my_action_pkg/SerialCommResult.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SERIALCOMMRESULT_H
#define MY_ACTION_PKG_MESSAGE_SERIALCOMMRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct SerialCommResult_
{
  typedef SerialCommResult_<ContainerAllocator> Type;

  SerialCommResult_()
    : received_data()
    , success(false)  {
    }
  SerialCommResult_(const ContainerAllocator& _alloc)
    : received_data(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _received_data_type;
  _received_data_type received_data;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::my_action_pkg::SerialCommResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SerialCommResult_<ContainerAllocator> const> ConstPtr;

}; // struct SerialCommResult_

typedef ::my_action_pkg::SerialCommResult_<std::allocator<void> > SerialCommResult;

typedef boost::shared_ptr< ::my_action_pkg::SerialCommResult > SerialCommResultPtr;
typedef boost::shared_ptr< ::my_action_pkg::SerialCommResult const> SerialCommResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SerialCommResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SerialCommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommResult_<ContainerAllocator2> & rhs)
{
  return lhs.received_data == rhs.received_data &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SerialCommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62edef80754232488b116d882f60ca55";
  }

  static const char* value(const ::my_action_pkg::SerialCommResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62edef8075423248ULL;
  static const uint64_t static_value2 = 0x8b116d882f60ca55ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SerialCommResult";
  }

  static const char* value(const ::my_action_pkg::SerialCommResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"std_msgs/String received_data\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::my_action_pkg::SerialCommResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received_data);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialCommResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SerialCommResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SerialCommResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "received_data: ";
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.received_data);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SERIALCOMMRESULT_H
