// Generated by gencpp from file my_action_pkg/SerialCommFeedback.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SERIALCOMMFEEDBACK_H
#define MY_ACTION_PKG_MESSAGE_SERIALCOMMFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct SerialCommFeedback_
{
  typedef SerialCommFeedback_<ContainerAllocator> Type;

  SerialCommFeedback_()
    : partial_data()  {
    }
  SerialCommFeedback_(const ContainerAllocator& _alloc)
    : partial_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _partial_data_type;
  _partial_data_type partial_data;





  typedef boost::shared_ptr< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SerialCommFeedback_

typedef ::my_action_pkg::SerialCommFeedback_<std::allocator<void> > SerialCommFeedback;

typedef boost::shared_ptr< ::my_action_pkg::SerialCommFeedback > SerialCommFeedbackPtr;
typedef boost::shared_ptr< ::my_action_pkg::SerialCommFeedback const> SerialCommFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.partial_data == rhs.partial_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "547b9faab8ee672f68a3e150a5914059";
  }

  static const char* value(const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x547b9faab8ee672fULL;
  static const uint64_t static_value2 = 0x68a3e150a5914059ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SerialCommFeedback";
  }

  static const char* value(const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"std_msgs/String partial_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.partial_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialCommFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SerialCommFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SerialCommFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "partial_data: ";
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.partial_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SERIALCOMMFEEDBACK_H
