// Generated by gencpp from file my_action_pkg/SerialCommAction.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SERIALCOMMACTION_H
#define MY_ACTION_PKG_MESSAGE_SERIALCOMMACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_action_pkg/SerialCommActionGoal.h>
#include <my_action_pkg/SerialCommActionResult.h>
#include <my_action_pkg/SerialCommActionFeedback.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct SerialCommAction_
{
  typedef SerialCommAction_<ContainerAllocator> Type;

  SerialCommAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  SerialCommAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_action_pkg::SerialCommActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::my_action_pkg::SerialCommActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::my_action_pkg::SerialCommActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::my_action_pkg::SerialCommAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SerialCommAction_<ContainerAllocator> const> ConstPtr;

}; // struct SerialCommAction_

typedef ::my_action_pkg::SerialCommAction_<std::allocator<void> > SerialCommAction;

typedef boost::shared_ptr< ::my_action_pkg::SerialCommAction > SerialCommActionPtr;
typedef boost::shared_ptr< ::my_action_pkg::SerialCommAction const> SerialCommActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SerialCommAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SerialCommAction_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SerialCommAction_<ContainerAllocator1> & lhs, const ::my_action_pkg::SerialCommAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SerialCommAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SerialCommAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SerialCommAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2b5abd3231abba3236b55ff2cd14cca";
  }

  static const char* value(const ::my_action_pkg::SerialCommAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2b5abd3231abba3ULL;
  static const uint64_t static_value2 = 0x236b55ff2cd14ccaULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SerialCommAction";
  }

  static const char* value(const ::my_action_pkg::SerialCommAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"SerialCommActionGoal action_goal\n"
"SerialCommActionResult action_result\n"
"SerialCommActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"SerialCommGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal definition\n"
"std_msgs/String data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SerialCommResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"std_msgs/String received_data\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"SerialCommFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: my_action_pkg/SerialCommFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"std_msgs/String partial_data\n"
;
  }

  static const char* value(const ::my_action_pkg::SerialCommAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialCommAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SerialCommAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SerialCommAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::my_action_pkg::SerialCommActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::my_action_pkg::SerialCommActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::my_action_pkg::SerialCommActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SERIALCOMMACTION_H
