// Generated by gencpp from file my_action_pkg/SPICommFeedback.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SPICOMMFEEDBACK_H
#define MY_ACTION_PKG_MESSAGE_SPICOMMFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace my_action_pkg
{
template <class ContainerAllocator>
struct SPICommFeedback_
{
  typedef SPICommFeedback_<ContainerAllocator> Type;

  SPICommFeedback_()
    : status()
    , current_data(0)  {
    }
  SPICommFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , current_data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _status_type;
  _status_type status;

   typedef uint8_t _current_data_type;
  _current_data_type current_data;





  typedef boost::shared_ptr< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SPICommFeedback_

typedef ::my_action_pkg::SPICommFeedback_<std::allocator<void> > SPICommFeedback;

typedef boost::shared_ptr< ::my_action_pkg::SPICommFeedback > SPICommFeedbackPtr;
typedef boost::shared_ptr< ::my_action_pkg::SPICommFeedback const> SPICommFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SPICommFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SPICommFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::SPICommFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.current_data == rhs.current_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SPICommFeedback_<ContainerAllocator1> & lhs, const ::my_action_pkg::SPICommFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf8e23de04e136de85afd80a9deeef55";
  }

  static const char* value(const ::my_action_pkg::SPICommFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf8e23de04e136deULL;
  static const uint64_t static_value2 = 0x85afd80a9deeef55ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SPICommFeedback";
  }

  static const char* value(const ::my_action_pkg::SPICommFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback definition\n"
"std_msgs/String status    # 状态描述\n"
"uint8 current_data         # 当前数据\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::my_action_pkg::SPICommFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.current_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPICommFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SPICommFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SPICommFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SPICOMMFEEDBACK_H
