// Generated by gencpp from file my_action_pkg/SPICommResult.msg
// DO NOT EDIT!


#ifndef MY_ACTION_PKG_MESSAGE_SPICOMMRESULT_H
#define MY_ACTION_PKG_MESSAGE_SPICOMMRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_action_pkg
{
template <class ContainerAllocator>
struct SPICommResult_
{
  typedef SPICommResult_<ContainerAllocator> Type;

  SPICommResult_()
    : success(false)
    , received_data(0)  {
    }
  SPICommResult_(const ContainerAllocator& _alloc)
    : success(false)
    , received_data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _received_data_type;
  _received_data_type received_data;





  typedef boost::shared_ptr< ::my_action_pkg::SPICommResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_action_pkg::SPICommResult_<ContainerAllocator> const> ConstPtr;

}; // struct SPICommResult_

typedef ::my_action_pkg::SPICommResult_<std::allocator<void> > SPICommResult;

typedef boost::shared_ptr< ::my_action_pkg::SPICommResult > SPICommResultPtr;
typedef boost::shared_ptr< ::my_action_pkg::SPICommResult const> SPICommResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_action_pkg::SPICommResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_action_pkg::SPICommResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_action_pkg::SPICommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::SPICommResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.received_data == rhs.received_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_action_pkg::SPICommResult_<ContainerAllocator1> & lhs, const ::my_action_pkg::SPICommResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_action_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_action_pkg::SPICommResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_action_pkg::SPICommResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_action_pkg::SPICommResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd859be5df4a4deddd82d57267b561dd";
  }

  static const char* value(const ::my_action_pkg::SPICommResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd859be5df4a4dedULL;
  static const uint64_t static_value2 = 0xdd82d57267b561ddULL;
};

template<class ContainerAllocator>
struct DataType< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_action_pkg/SPICommResult";
  }

  static const char* value(const ::my_action_pkg::SPICommResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result definition\n"
"bool success               # 操作是否成功\n"
"uint8 received_data        # 接收到的数据\n"
;
  }

  static const char* value(const ::my_action_pkg::SPICommResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.received_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SPICommResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_action_pkg::SPICommResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_action_pkg::SPICommResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "received_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ACTION_PKG_MESSAGE_SPICOMMRESULT_H
